package org.lowcarbon.soda.ui.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KEY_WORD".
*/
public class KeyWordDao extends AbstractDao<KeyWord, Void> {

    public static final String TABLENAME = "KEY_WORD";

    /**
     * Properties of entity KeyWord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Keyword = new Property(0, String.class, "keyword", false, "KEYWORD");
        public final static Property Count = new Property(1, long.class, "count", false, "COUNT");
        public final static Property Time = new Property(2, long.class, "time", false, "TIME");
        public final static Property Type = new Property(3, int.class, "type", false, "TYPE");
    }


    public KeyWordDao(DaoConfig config) {
        super(config);
    }
    
    public KeyWordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KEY_WORD\" (" + //
                "\"KEYWORD\" TEXT NOT NULL ," + // 0: keyword
                "\"COUNT\" INTEGER NOT NULL ," + // 1: count
                "\"TIME\" INTEGER NOT NULL ," + // 2: time
                "\"TYPE\" INTEGER NOT NULL );"); // 3: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KEY_WORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KeyWord entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getKeyword());
        stmt.bindLong(2, entity.getCount());
        stmt.bindLong(3, entity.getTime());
        stmt.bindLong(4, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KeyWord entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getKeyword());
        stmt.bindLong(2, entity.getCount());
        stmt.bindLong(3, entity.getTime());
        stmt.bindLong(4, entity.getType());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public KeyWord readEntity(Cursor cursor, int offset) {
        KeyWord entity = new KeyWord( //
            cursor.getString(offset + 0), // keyword
            cursor.getLong(offset + 1), // count
            cursor.getLong(offset + 2), // time
            cursor.getInt(offset + 3) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KeyWord entity, int offset) {
        entity.setKeyword(cursor.getString(offset + 0));
        entity.setCount(cursor.getLong(offset + 1));
        entity.setTime(cursor.getLong(offset + 2));
        entity.setType(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(KeyWord entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(KeyWord entity) {
        return null;
    }

    @Override
    public boolean hasKey(KeyWord entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
